openapi: 3.0.0
info:
  version: '1.1.0'
  title: 'EvolutioAPI'
  license:
    name: MIT
servers:
  - url: '/api'
paths:
  /orders:
    get:
      summary: 'Returns details about orders and its deliveries'
      operationId: getInfoAboutOrdersDeliveries
      security: []
      tags:
        - orders
      parameters:
        - name: brand_id
          in: query
          description: 'Brand_id of order'
          required: true
          schema:
              type: integer
              format: int32
        - name: cursor
          in: query
          description: 'Cursor to another page'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Orders data. Page size is set to 2'
          content:
            application/json:
              schema:
                type: object
                properties:
                  next:
                    type: string
                    description: 'Link to the next page with results'
                  previous:
                    type: string
                    description: 'Link to the previous page with results'
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '404':
          description: "Didn't find any records"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'
  /products:
    get:
      summary: 'Returns overall quantity of each product in order'
      operationId: getQuantityProductInOrder
      security: []
      tags:
        - orders
      parameters:
        - in: query
          name: filter
          description: 'Pass either id of the order or reference'
          required: true
          style: form
          explode: true
          schema:
            type: object
            oneOf:
              - properties:
                  id:
                    type: integer
                    format: int32
                required: [id]
                additionalProperties: false
              - properties:
                  reference:
                    type: string
                required: [reference]
                additionalProperties: false
      responses:
        '200':
          description: 'Products quantity info'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: "Didn't find any records"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'
security:
  - TokenAuth: []

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          description: 'Id of order'
          type: integer
          format: int32
        brand_id:
          description: 'Brand id of order'
          type: integer
          format: int32
        reference:
          description: 'Reference of order'
          type: string
        date_of_creation:
          description: 'Date time when order created'
          type: string
          format: date-time
        price_total:
          description: 'Price of order'
          type: number
          format: double
        deliveries:
          type: array
          items:
            $ref: '#/components/schemas/Delivery'
    Delivery:
      type: object
      properties:
        id:
          description: 'Id of the delivery'
          type: integer
          format: int32
        shipped:
          description: 'Is shipped'
          type: boolean
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        quantity:
          description: 'Overall quantity of certain product for given query'
          type: integer
          format: int32
        name:
          description: 'Name of the product'
          type: string
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
