openapi: 3.0.0
info:
  version: '1.1.0'
  title: 'OceanAPI'
  license:
    name: MIT
servers:
  - url: 'localhost:8001/api'
paths:
  /orders:
    get:
      summary: 'Returns details about orders and its deliveries'
      operationId: getInfoAboutOrdersDeliveries
      security: []
      tags:
        - orders
      parameters:
        - name: brand_id
          in: query
          required: true
          schema:
              type: integer
              format: int32
      responses:
        '200':
          description: 'Orders data'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: "Didn't find any records"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'
  /products/:
    get:
      summary: 'Returns overall quantity of each product in order'
      operationId: getQuantityProductInOrder
      security: []
      tags:
        - investing
      parameters:
      parameters:
        - in: query
          name: filter
          required: true
          style: form
          explode: true
          schema:
            type: object
            properties:
              username:
                type: string
              site:
                type: string
              survey:
                type: string
            minProperties: 1
            maxProperties: 1
            additionalProperties: false
      responses:
        '200':
          description: 'Celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryId'
                type: object
                properties:
                  number:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: {}
  /cian/{building_type}/{deal_type}/{region}:
    get:
      summary: 'Returns celery_task_id for Cian market'
      operationId: cianCeleryIdGet
      security: []
      tags:
        - cian
      parameters:
        - name: building_type
          in: path
          description: Type of building
          required: true
          schema:
            type: string
            enum: [office, flat_new, flat_old, building, warehouse, trading area, land plot]
          examples:
            office:
              value: flat_old
              summary: вторичка
            flat_new:
              value: flat_new
              summary: первичка
        - name: deal_type
          in: path
          description: Type of deal
          required: true
          schema:
              type: string
              enum: ['rent', 'sale']
        - name: region
          in: path
          description: Region
          required: true
          schema:
              type: string
              enum: ['Москва', 'Московская область', 
                     'Санкт-Петербург', 'Ленинградская область',
                     'Новосибирск', 'Новосибирская область',
                     'Екатеринбург', 'Свердловская область',
                     'Казань', 'Республика Татарстан',
                     'Нижний Новгород', 'Нижегородская область',
                     'Челябинск', 'Челябинская область',
                     'Самара', 'Самарская область',
                     'Омск', 'Омская область',
                     'Ростов-на-Дону', 'Ростовская область',
                     'Уфа', 'Республика Башкортостан',
                     'Красноярск', 'Красноярский край',
                     'Воронеж', 'Воронежская область',
                     'Пермь', 'Пермский край',
                     'Волгоград', 'Волгоградская область',
                     'Города миллионники', 'Регионы'
              ]
      responses:
        '200':
          description: 'Found celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cian'
        '404':
          description: "Didn't find celery task id"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'

components:
  schemas:
    Order:
      type: object
      required:
        - celery_task_id
      properties:
        id:
          type: integer
          format: int32
        brand_id:
          type: integer
          format: int32
        reference:
          type: string
        date_of_creation:
          type: string
          format: date-time
        price_total:
          type: number
          format: double
        deliveries:
          type: array
          items:
            $ref: '#/components/schemas/Delivery'
    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: int32
        shipped:
          type: boolean
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        name:
          type: string  
