openapi: 3.0.0
info:
  version: '1.1.0'
  title: 'EvolutioAPI'
  license:
    name: MIT
servers:
  - url: '/api'
paths:
  /orders:
    get:
      summary: 'Returns details about orders and its deliveries'
      operationId: getInfoAboutOrdersDeliveries
      security: []
      tags:
        - orders
      parameters:
        - name: brand_id
          in: query
          required: true
          schema:
              type: integer
              format: int32
      responses:
        '200':
          description: 'Orders data'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: "Didn't find any records"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'
  /products:
    get:
      summary: 'Returns overall quantity of each product in order'
      operationId: getQuantityProductInOrder
      security: []
      tags:
        - orders
      parameters:
        - in: query
          name: filter
          required: true
          style: form
          explode: true
          schema:
            type: object
            oneOf:
              - properties:
                  id:
                    type: integer
                    format: int32
                required: [id]
                additionalProperties: false
              - properties:
                  reference:
                    type: string
                required: [reference]
                additionalProperties: false
      responses:
        '200':
          description: 'Products quantity info'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: "Didn't find any records"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'
components:
  schemas:
    Order:
      type: object
      required:
        - celery_task_id
      properties:
        id:
          type: integer
          format: int32
        brand_id:
          type: integer
          format: int32
        reference:
          type: string
        date_of_creation:
          type: string
          format: date-time
        price_total:
          type: number
          format: double
        deliveries:
          type: array
          items:
            $ref: '#/components/schemas/Delivery'
    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: int32
        shipped:
          type: boolean
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        name:
          type: string  
