openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'InvestingAPI'
  license:
    name: MIT
servers:
  - url: '95.165.130.22:8001/api'
paths:
  /investing/{celery_task_id}/:
    get:
      summary: 'Returns details about created task'
      operationId: getInfoAboutTask
      security:
        - {}
      tags:
        - investing
      parameters:
        - name: celery_task_id
          in: path
          required: true
          schema:
              type: string
          examples:
            office:
              value: office
              summary: это если офисы хотим
            flat_new:
              value: flat_new
              summary: это если аренду
      responses:
        '200':
          description: 'Celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvestingTaskInfo'
  /investing/:
    post:
      summary: 'Returns celery_task_id of created task'
      operationId: initiateInvestingTask
      security:
        - {}
      tags:
        - investing
      requestBody:
        description: 'TIKER of company' 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tiker'
            examples:
              Kidpik Corp.:
                value: 
                  tiker: NASDAQCM:PIK
                summary: Kинформация о Kidpik Corp.
      responses:
        '200':
          description: 'Celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryId'
                type: object
                properties:
                  number:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: {}
components:
  schemas:
    Tiker:
      type: object
      required: 
        - tiker
      properties:
        tiker:
          type: string
    CeleryId:
      type: object
      properties:
        celery_task_id:
          type: string
    InvestingTaskInfo:
      type: object
      properties:
        ni:
          type: object
          properties:
              Q:
                type: object
                additionalProperties: {}
              LTM:
                type: object
                additionalProperties: {}
              FY:
                type: object
                additionalProperties: {}
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
