openapi: 3.0.0
info:
  version: '1.1.0'
  title: 'OceanAPI'
  license:
    name: MIT
servers:
  - url: '/api'
paths:
  /investing/{celery_task_id}/:
    get:
      summary: 'Returns details about created task'
      operationId: getInfoAboutTask
      security: []
      tags:
        - investing
      parameters:
        - name: celery_task_id
          in: path
          required: true
          schema:
              type: string
      responses:
        '200':
          description: 'Task data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvestingTaskInfo'
        '201':
          description: 'Task in process'
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: string
                    enum: ['task in progress']
  /investing/:
    post:
      summary: 'Returns celery_task_id of created task'
      operationId: initiateInvestingTask
      security: []
      tags:
        - investing
      requestBody:
        description: 'TIKER of company' 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tiker'
            examples:
              Kidpik Corp.:
                value: 
                  tiker: NASDAQCM:PIK
                summary: Kинформация о Kidpik Corp.
      responses:
        '200':
          description: 'Celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryId'
                type: object
                properties:
                  number:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: {}
  /cian/{building_type}/{deal_type}/{region}:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      security: []
      tags:
        - cian
      parameters:
        - name: building_type
          in: path
          description: Type of building
          required: true
          schema:
            type: string
            enum: [office, flat_new, flat_old, building, warehouse, trading area, land plot]
          examples:
            office:
              value: flat_old
              summary: вторичка
            flat_new:
              value: flat_new
              summary: первичка
        - name: deal_type
          in: path
          description: Type of deal
          required: true
          schema:
              type: string
              enum: ['rent', 'sale']
        - name: region
          in: path
          description: Region
          required: true
          schema:
              type: string
              enum: ['Москва', 'Московская область', 
                     'Санкт-Петербург', 'Ленинградская область',
                     'Новосибирск', 'Новосибирская область',
                     'Екатеринбург', 'Свердловская область',
                     'Казань', 'Республика Татарстан',
                     'Нижний Новгород', 'Нижегородская область',
                     'Челябинск', 'Челябинская область',
                     'Самара', 'Самарская область',
                     'Омск', 'Омская область',
                     'Ростов-на-Дону', 'Ростовская область',
                     'Уфа', 'Республика Башкортостан',
                     'Красноярск', 'Красноярский край',
                     'Воронеж', 'Воронежская область',
                     'Пермь', 'Пермский край',
                     'Волгоград', 'Волгоградская область',
                     'Города миллионники', 'Регионы'
              ]
      responses:
        '200':
          description: 'Found celery task id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cian'
        '404':
          description: "Didn't find celery task id"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
              examples:
                Not found:
                  description: 'The only response possible'
                  value:
                    detail: 'Not found.'

components:
  schemas:
    Cian:
      type: object
      required:
        - celery_task_id
      properties:
        celery_task_id:
          type: string
    Tiker:
      type: object
      required: 
        - tiker
      properties:
        tiker:
          type: string
    CeleryId:
      type: object
      properties:
        celery_task_id:
          type: string
    InvestingTaskInfo:
      type: object
      properties:
        ni:
          type: object
          description: 'Net Income Reconciliation'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        ebitda:
          type: object
          description: 'EBITDA Reconciliation'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        forecasts:
          type: object
          description: 'Forecasts'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        valuation:
          type: object
          description: 'Valuation Ratios'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        balance_sheet:
          type: object
          description: 'Balance Sheet'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        income_statement:
          type: object
          description: 'Income Statement'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
        cashflow_statement:
          type: object
          description: 'Cash Flow Statement'
          properties:
              Q:
                description: 'period: Fiscal Quarter'
                type: object
                additionalProperties: {}
              LTM:
                description: 'period: Latest Twelve Month'
                type: object
                additionalProperties: {}
              FY:
                description: 'period: Fiscal Year'
                type: object
                additionalProperties: {}
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
